baseURL = "https://bioxray.dk/"
languageCode = 'en-dk'
title = "MOK's Onomatomaniske Kaos"

# pygmentsstyle = "trac"
#pygmentsstyle = "wombat"
pygmentsstyle = "monokailight"

# Length of summary in words
#summaryLength = 30

[params]
slogan = "Super Cool"
theme = "light"
footer = '© Morten Kjeldgaard, 2024'

paginate = 4

[taxonomies]
  category = 'categories'
  tag = 'tags'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 20

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 30

# [[menu.main]]
#     identifier = "contact"
#     name = "Contact"
#     url = "/contacts"
#     weight = 40

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[sitemap]
   changefreq = "weekly"
   filename = "sitemap.xml"
   priority = 0.5
